name: Publish package to NPM

on:
  push:
    branches:
      - master

name: Publish Package
jobs:
  release:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Use this GitHub Action
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        with:
          COMMIT_DISABLED: 1

      - name: Install Package dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Publish
        run: yarn publish --access=restricted
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}