name: Publish package to NPM

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: yarn
      - run: yarn build
      - run: yarn publish --access=private
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
